apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  database: "postgres"
  host: "aws-0-ap-south-1.pooler.supabase.com"
  pool_mode: "transaction"
  port: "6543"
  user: "postgres.cggaxfiogbsfikjhecum"
